### ISSUE TITLE
这个代码有对应的论文吗，可以把论文的名字发出来吗？  Is there a corresponding paper for this code? Can the name of the paper be sent out?

### ISSUE THREAD

**Issue by gaozhen123456** [sausthapit/ComputationOffloadingRL#1]
这个代码有对应的论文吗，可以把论文的名字发出来吗？

Is there a corresponding paper for this code? Can the name of the paper be sent out?

**Comment by gaozhen123456** [comment]
这个代码有对应的论文吗，可以把论文的名字发出来吗？

Is there a corresponding paper for this code? Can the name of the paper be sent out?

**Comment by gaozhen123456** [comment]
这个代码有对应的论文吗，可以把论文的名字发出来吗？

Is there a corresponding paper for this code? Can the name of the paper be sent out?

**Comment by gaozhen123456** [comment]
这个代码有对应的论文吗，可以把论文的名字发出来吗？

Is there a corresponding paper for this code? Can the name of the paper be sent out?

**Comment by gaozhen123456** [comment]
这个代码有对应的论文吗，可以把论文的名字发出来吗？

Is there a corresponding paper for this code? Can the name of the paper be sent out?

**Comment by gaozhen123456** [comment]
这个代码有对应的论文吗，可以把论文的名字发出来吗？

Is there a corresponding paper for this code? Can the name of the paper be sent out?

**Comment by gaozhen123456** [comment]
这个代码有对应的论文吗，可以把论文的名字发出来吗？

Is there a corresponding paper for this code? Can the name of the paper be sent out?

**Comment by sausthapit** [comment]
Hi the paper is in the review process. I will update it once the process is completed.
